import Vue from 'vue'
import {
    Button,
    Form,
    FormItem,
    Input,
    Container,
    Header,
    Aside,
    Main,
    Footer,
    Menu,
    Submenu,
    MenuItem,
    Breadcrumb,
    BreadcrumbItem,
    Card,
    Row,
    Col,
    Table,
    TableColumn,
    Switch,
    Tooltip,
    Pagination,
    Loading,
    Dialog,
    Tag,
    Calendar,
    Select,
    Option,
    Tree,
    Avatar,
    Dropdown,
    DropdownItem,
    DropdownMenu,
    Cascader,
    Steps,
    Step,
    Drawer,
    Autocomplete,
    Progress,
    Divider,
    Collapse,
    CollapseItem,
    Radio,
    Timeline,
    TimelineItem,
    Tabs,
    TabPane,
    Upload,
    Checkbox,
    Badge,
    DatePicker,
} from 'element-ui'

Vue.use(DatePicker)
Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItem)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Card)
Vue.use(Row)
Vue.use(Col)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Switch)
Vue.use(Tooltip)
Vue.use(Pagination)
Vue.use(Loading)
Vue.use(Dialog)
Vue.use(Tag)
Vue.use(Calendar)
Vue.use(Select)
Vue.use(Option)
Vue.use(Tree)
Vue.use(Avatar)
Vue.use(Dropdown)
Vue.use(DropdownItem)
Vue.use(DropdownMenu)
Vue.use(Cascader)
Vue.use(Steps)
Vue.use(Step)
Vue.use(Drawer)
Vue.use(Autocomplete)
Vue.use(Progress)
Vue.use(Divider)
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(Radio)
Vue.use(Timeline)
Vue.use(TimelineItem)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Upload)
Vue.use(Checkbox)
Vue.use(Footer)
Vue.use(Badge)